### PR TITLE
Support subscripts

### PR DESCRIPTION
**Pull request by gordonwatts**
Finally! Summary of changes:

 - Move to using requirements.txt rather than setup.py
 - Bump version of `func_adl` to use the new version of `qastle` that supports subscripts
 - Added a test to explicitly look at @mweinberg2718 's performance test

I checked this runs integrated tests. I believe this is ready to merge after review.

### CODE REVIEW

**Comment by gordonwatts** [comment]
I'm running a full suite of performance tests now - we'll see how the speeds look. But on `river` the same test is varying from 90 seconds to 190 seconds - so the jitter in testing is quite large.

**Comment by BenGalewsky** [comment]
Do you have an example select that didn't work without this fix and does work now?

**Comment by gordonwatts** [comment]
Crap. Just saw this. Yes - @mweinberg2718 's 8 column request - to do it "nicely" requires indexing.

```
(call ResultTTree (call Select (call Select (call EventDataset (list 'localds:bogus')) (lambda (list e) (list (call (attr e 'Electrons') 'Electrons') (call (attr e 'Muons') 'Muons')))) (lambda (list e) (list (call (attr (subscript e 0) 'Select') (lambda (list ele) (call (attr ele 'e')))) (call (attr (subscript e 0) 'Select') (lambda (list ele) (call (attr ele 'pt')))) (call (attr (subscript e 0) 'Select') (lambda (list ele) (call (attr ele 'phi')))) (call (attr (subscript e 0) 'Select') (lambda (list ele) (call (attr ele 'eta')))) (call (attr (subscript e 1) 'Select') (lambda (list mu) (call (attr mu 'e')))) (call (attr (subscript e 1) 'Select') (lambda (list mu) (call (attr mu 'pt')))) (call (attr (subscript e 1) 'Select') (lambda (list mu) (call (attr mu 'phi')))) (call (attr (subscript e 1) 'Select') (lambda (list mu) (call (attr mu 'eta'))))))) (list 'e_E' 'e_pt' 'e_phi' 'e_eta' 'mu_E' 'mu_pt' 'mu_phi' 'mu_eta') 'forkme' 'dude.root')
```

**Comment by gordonwatts** [comment]
In this workflow - who does the merging? @BenGalewsky or me?

**Comment by BenGalewsky** [comment]
This PR became stale and has been subsumed into pr #12

**Pull request closed without merging**
